import { getFormBoolean, getFormValue, getFormValues } from "./form-data";

export function buildModelFormPayload(form: FormData) {
  return {
    developer: getFormValue(form, "developer"),
    modelId: getFormValue(form, "modelId"),
    name: getFormValue(form, "name"),
    icon: getFormValue(form, "icon"),
    officialUrl: getFormValue(form, "officialUrl"),
    group: getFormValue(form, "group"),
    type: getFormValue(form, "type"),
    notes: getFormValue(form, "notes"),
    supportsToolCalling: getFormBoolean(form, "supportsToolCalling"),
    supportsVision: getFormBoolean(form, "supportsVision"),
    supportsTemperatureControl: getFormBoolean(form, "supportsTemperatureControl"),
    supportsReasoning: getFormBoolean(form, "supportsReasoning"),
    reasoningEffortLevels: getFormValues(form, "reasoningEffortLevels"),
    supportsWebSearch: getFormBoolean(form, "supportsWebSearch"),
    inputText: getFormBoolean(form, "inputText"),
    inputImage: getFormBoolean(form, "inputImage"),
    inputAudio: getFormBoolean(form, "inputAudio"),
    inputVideo: getFormBoolean(form, "inputVideo"),
    outputText: getFormBoolean(form, "outputText"),
    outputImage: getFormBoolean(form, "outputImage"),
    outputAudio: getFormBoolean(form, "outputAudio"),
    outputVideo: getFormBoolean(form, "outputVideo"),
    inputCostPerMTokens: getFormValue(form, "inputCostPerMTokens"),
    outputCostPerMTokens: getFormValue(form, "outputCostPerMTokens"),
    cacheReadCostPerMTokens: getFormValue(form, "cacheReadCostPerMTokens"),
    cacheWriteCostPerMTokens: getFormValue(form, "cacheWriteCostPerMTokens"),
    contextWindow: getFormValue(form, "contextWindow"),
    maxOutputTokens: getFormValue(form, "maxOutputTokens"),
    knowledgeCutoff: getFormValue(form, "knowledgeCutoff"),
    releaseDate: getFormValue(form, "releaseDate"),
    lastUpdated: getFormValue(form, "lastUpdated"),
    isActive: getFormBoolean(form, "isActive"),
    showOnHome: getFormBoolean(form, "showOnHome"),
  };
}
